config/routes.rb
Rails.application.routes.draw do
  resources :user_orders, only: [:create]  
  resources :reviews, only: [:create]
  resources :food_items
  root 'wellcome#index'

  get 'menu' => 'wellcome#menu'
  
  get 'contact' => 'wellcome#contact'

  get 'order' => 'wellcome#order'

  get 'check' => 'wellcome#check_out'

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  has_many :reviews
  def self.search(query)
    where("lower(name) like ?", "%#{query}%")
  end
end

app/models/order_list.rb
class OrderList < ActiveRecord::Base
  belongs_to :user_order
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :food_item
end

app/models/user_order.rb
class UserOrder < ActiveRecord::Base
  has_many :order_lists
  attr_accessor :coupon_code

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item.view ||= 0
    @food_item.view += 1
    @food_item.save!
    url = @food_item.image_url.split("/").last
    @bigger_url = "http://loremflickr.com/640/640/" + url
    @review = Review.new
    @reviews = @food_item.reviews
    unless @reviews.nil?
      star_avg = 0.0
      @reviews.each do |r| 
        star_avg += r.star 
      end
      star_avg = star_avg / @reviews.count
      if (star_avg.nan?)
        @food_item.star_avg = 0.0
        @food_item.save!
      else
        @food_item.star_avg = star_avg
        @food_item.save!
      end
    end
    
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :image_url, :cuisine)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  	   @food = FoodItem.find(params[:food_item_id])
	   @review = @food.reviews.create(review_params)

	   if @review.save
	     redirect_to @food
	   else
	   	 redirect_to @food
	   end
  end

  private

  def review_params
    params.require(:review).permit(:star, :text)
  end
end

app/controllers/user_orders_controller.rb
class UserOrdersController < ApplicationController
  def create
   @user = UserOrder.new(user_order_params)

   if @user.save
     @list = @user.order_lists.create(list: params[:order_list], coupon_code: coupon_params)
     flash[:success] = "OK"
     redirect_to check_path(order_list_id: @list.id)
   else
     redirect_to order_path
   end
    
  end

  private

  def user_order_params
    params.require(:user_order).permit(:name, :address, :number)
  end

  def coupon_params
    params.require(:user_order)[:coupon_code]
  end
end

app/controllers/wellcome_controller.rb
class WellcomeController < ApplicationController
  def index
  end

  def menu
    @sections = %w(Breakfast Lunch Dinner Drinks)
    @food_items = filter_food_item_by_section(params[:section])
    push_food_item_to_cart(params[:order])
    pop_food_item_out_of_cart(params[:un_order])
    @food_items = sort_food_item_by_sort_params(params[:sort], @food_items)
    @food_items = filter_food_item_by_cuisine_params(params[:cuisine], @food_items)
    @food_items = filter_by_search_params(params[:search],@food_items)
  end

  def contact
  end


  def order
    push_food_item_to_cart(params[:order])
    pop_food_item_out_of_cart(params[:un_order])
    if(session[:order_ids].blank?)
      redirect_to menu_path
    end
    @foods = []
    session[:order_ids].each do |id|
      @foods << FoodItem.find(id)
    end
    @total_price = 0
    @user = UserOrder.new
  end

  def check_out
    if(flash[:success].nil?)
      redirect_to menu_path
    end
    @order = OrderList.find(params[:order_list_id])
    @orders = []
    orders_lists = @order.list.split(" ")
    orders_lists.each do |o|
      @orders << FoodItem.find(o.to_i)
    end 
    @user = UserOrder.find(@order.user_order_id)
    @total_price = 0
    session.delete(:order_ids)
  end

  private

  def filter_food_item_by_section(sections)
    if sections.blank?
      @foods = FoodItem.all
    else
      @foods = FoodItem.where(section: sections)
    end
  end

  def push_food_item_to_cart(order)
    unless order.blank?
      (session[:order_ids] ||= []) << order
    end
  end

  def pop_food_item_out_of_cart(un_order)
    unless un_order.blank?
      session[:order_ids].delete(un_order)
    end
  end

  def sort_food_item_by_sort_params(params, food)
    case params
    when "alphabetical"
      food = food.sort { |a,b| a.name.downcase <=> b.name.downcase } 
    when "price low to high"
      food = food.sort { |a,b| a.price <=> b.price}
    when "price high to low"
      food = food.sort { |a,b| b.price <=> a.price}
    when "view"
      food = food.sort { |a,b| b.view <=> a.view}
    end
    food
  end
  
  def filter_food_item_by_cuisine_params(params, food)
    case params
    when "Pork"
      food = food.select { |f| f.cuisine == "Pork"}
    when "Chicken"
      food = food.select { |f| f.cuisine == "Chicken"}
    when "Fish"
      food = food.select { |f| f.cuisine == "Fish"}
    when "Beef"
      food = food.select { |f| f.cuisine == "Beef"}
    end
    food
  end

  def filter_by_search_params(search,food)
    unless search.nil?
      food = food.search(search)
    end
    food
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def is_active(ctrl, act)
    	if (controller.controller_name == ctrl) && (controller.action_name == act)
    		"active"
    	else
    		""
    	end

    end

end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_orders_helper.rb
module UserOrdersHelper
end

app/helpers/wellcome_helper.rb
module WellcomeHelper
end

app/views/food_items/_food_item.html.erb
<div class="col-xl-4 col-md-6 col-sm-12">
  <div class="card" style="box-shadow: 2px 2px 4px #000000;">
    <%=link_to image_tag(food_item.image_url, class:"card-img-top img-fluid", alt:"Card image cap"), food_item_path(food_item) %>
    <div class="card-block" >
      <h3 class="card-title" style="text-shadow: 2px 2px 4px #D8C0D5;">
        <strong><%= food_item.name %></strong>
      </h3>
      <p class="card-text" >
         <%= food_item.description  %>
      </p>
      <h5 class="text-xs-right">
        <span class="label label-pill label-primary">
          <%= food_item.price %> VND
        </span>
      </h5>
      <hr>
        <div class="text-xs-center">
          <div class="btn-group">
            <%= link_to "Đặt hàng", order_path(order: food_item.id), 
              class: "btn btn-secondary"%>
            <% if session[:order_ids].nil? %>
             <%= link_to "Đặt vào giỏ hàng",
              menu_path(order: food_item.id, section: params[:section]), 
              class: "btn btn-secondary" %>
            <% else  %>
             <% if session[:order_ids].include? food_item.id.to_s %>
              <%= link_to "Bỏ khỏi giỏ hàng",
                menu_path(un_order: food_item.id, section: params[:section]), 
                class: "btn btn-secondary" %>
            <% else  %>
              <%= link_to "Đặt vào giỏ hàng",
                menu_path(order: food_item.id, section: params[:section]), 
                class: "btn btn-secondary" %>
            <% end %>
        <% end %>
          </div>
        </div>
    </div>
    <div class="card-footer text-muted">
       <small >
         <%=  pluralize(food_item.view,"view")  %> 
         <% if (food_item.star_avg != 0.0) && (!food_item.star_avg.nil?)%>
           | star: <%= food_item.star_avg.round(2) %>/5.0
         <% end %>
       </small>
       <small class="pull-xs-right">
         Posted at: <%= food_item.created_at.strftime('%Y-%m-%d')  %>
       </small>
    </div>
  </div>
</div>

app/views/food_items/_form.html.erb
<%= form_for(@food_item) do |f| %>
  <% if @food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% @food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :cuisine,"Cuisine" %><br>
    <%= f.select :cuisine, ['Pork','Chicken','Fish','Beef'] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Food Items</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= food_item.cuisine %></td>
        <td><%= image_tag food_item.image_url, class:"img-thumbnail" %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-7">
    <%= image_tag @bigger_url, class:"img-fluid img-thumbnail" %>
  </div>
  <div class="col-xs-5 pull-xs-left">
    <h1>
      <%= @food_item.name %>
    </h1>
    <hr> 
    <h5>
      <strong>Description:</strong>
      <%= @food_item.description %>
    </h5>
    
    <h5>
      <strong>Price:</strong>
      <div class="label label-primary">
        <%= @food_item.price %> VND
      </div>
    </h5>
    
    <h5>
      <strong>Section:</strong>
      <%= @food_item.section %>
    </h5> <h5>
      <strong>Cuisine:</strong>
      <%= @food_item.cuisine %>
    </h5>

    <h5>
      <div class="small text-muted">
        <strong>View:</strong>
        <%= @food_item.view %>
      </div>
    </h5>

    <h5>
      <div class="small text-muted">
        <strong>Posted at:</strong>
        <%= @food_item.created_at.strftime('%Y-%m-%d')  %>
      </div>
    </h5>    
    
    <div class="btn-group">
      <%= link_to "Đặt hàng", order_path(order: @food_item.id), 
        class: "btn btn-secondary"%>
      <% if session[:order_ids].nil? %>
       <%= link_to "Đặt vào giỏ hàng",
        menu_path(order: @food_item.id, section: params[:section]), 
        class: "btn btn-secondary" %>
      <% else  %>
       <% if session[:order_ids].include? @food_item.id.to_s %>
        <%= link_to "Bỏ khỏi giỏ hàng",
          menu_path(un_order: @food_item.id, section: params[:section]), 
          class: "btn btn-secondary" %>
        <% else  %>
          <%= link_to "Đặt vào giỏ hàng",
            menu_path(order: @food_item.id, section: params[:section]), 
            class: "btn btn-secondary" %>
        <% end %>
      <% end %>
    </div>
    <hr>
    Star: <%= @food_item.star_avg.round(2) %>/5.0
    <h4> Review: </h4>
      <% @reviews.each do |r| %>
        <h6 class="text-muted">
          <%= r.text %> | <%= r.star %> star<br>
        </h6>
      <% end %>
    <%= form_for @review, url: reviews_path(food_item_id: @food_item.id), html: {method: :post } do |f| %>
    <div class="form-group">
      <br>
      <%= f.label :star,"Star:" %>
      <%= f.select :star, [ 1,2,3,4,5 ],class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :text,"Review:" %>
      <%= f.text_area :text , class: "form-control", size: "12x12"%>
    </div>
    <div class="form_group text-xs-center">
      <%= f.submit "Commit", class: "btn btn-secondary btn-md" %>
      <%= link_to "Back to menu", menu_path, class: "btn btn-secondary btn-md" %>
    </div>
  <% end %>

    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sang Restaurent</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <%= render '/shared/navbar' %>
  <br>
    <%= yield %>
  <%= render '/shared/footer' %>
  </div>
</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
  <%= link_to "Sang Restaurent", root_path, class:"navbar-brand" %>
  <ul class="nav navbar-nav">
    <li class="nav-item <%= is_active("wellcome", "index") %>">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= is_active("wellcome", "menu") %>">
      <%= link_to "Menu", menu_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= is_active("wellcome", "contact") %>">
      <%= link_to "Contact us", contact_path, class: "nav-link" %>
    </li>
      <div class="pull-xs-right">
        <% unless (session[:order_ids] ||= []).blank? %>
            <li class="nav-item">
              <%= link_to "#{pluralize(session[:order_ids].count, "Item")} in the cart",
               "#" , class: "nav-link" %>
            </li>      
            <li class="nav-item">
              <%= link_to "Check out", order_path, 
              class: "nav-link #{controller.controller_name == "wellcome" && 
                controller.action_name == "order" ? "active" : ""}" %>
            </li>
        <% end %>
           <%= form_tag(menu_path, :method => "get", class: "nav-item form-inline pull-xs-right", id: "search-form") do %>
              <div class="input-append">
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Dish" %>
                <button class="btn btn-secondary-outline" type="submit">Search</button>
              </div> 
          <% end %>
      </div>
  </ul>
</nav>

app/views/shared/_slider.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img src="http://dummyimage.com/1200x500/000/545457" alt="First slide">
    </div>
    <div class="carousel-item">
      <img src="http://dummyimage.com/1200x500/000/545457" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img src="http://dummyimage.com/1200x500/000/545457" alt="Third slide">
    </div>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/wellcome/check_out.html.erb
<h1 class="text-xs-center display-4"> Thanks for your's order </h1>
<div class="row">
  <table class="table">
    <thead class="thead-default">
      <tr>
        <th>#</th>
        <th>Dish</th>
        <th>Price</th>
      </tr>
    </thead>
   <tbody>
     <% @orders.each_with_index do |dish, i|  %>
     <tr>
       <th scope="row"><%= i+1 %></th>
        <td><%= dish.name %></td>
        <td class="text-xs-right"><%= dish.price %> Đ</td>
     </tr>
     <% @total_price += dish.price %>
     <% end %>
      <tr>
        <td></td>
        <td></td>
        <% if @order.coupon_code == "CODERSCHOOL" %>
          <th class="text-xs-right">total price: 
            <%= (@total_price + 20000)*0.7 %> đ (included delivery cost and coupon)</th>
        <% else %>
          <th class="text-xs-right">total price: 
            <%= @total_price + 20000 %> đ (included delivery cost)</th>
        <% end %>
      </tr>
   </tbody>
  </table>
</div>
<h3 class="text-xs-center">Your's information</h3>
<h5><strong>Name:</strong> <%= @user.name %> </h5>
<h5><strong>Phone Number:</strong> <%= @user.number %> </h5>
<h5><strong>Addess:</strong> <%= @user.address %> </h5>
<h5><strong>Ordered at:</strong> <%= @order.created_at.strftime('%Y-%m-%d %H:%M') %></h5>
<div class="text-xs-center">
  <%= link_to "Back to menu", menu_path, class: "btn btn-secondary" %>
</div>

app/views/wellcome/contact.html.erb
<div class="row">
  <div class="text-xs-center">
    <h1> Citihub Co., Ltd </h1>
    <h2> 93bis Nguyen Van Thu, Dakao Ward, District 1 </h2>
    <h2> Phone: 01227909288 </h2>
    
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.27607239286!2d106.69721431487838!3d10.79015499231221!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528caa46c5bd7%3A0xde6c27ae7fac0e37!2sCitihub+Co-working+Space+%26+Coffee!5e0!3m2!1sen!2s!4v1457887938850" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/wellcome/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-xs-5">
      <h2>Wellcome to</h2> <br />
      <div class="display2">
        <h1><strong>Sang Restaurent</strong></h1> <br />
      </div>
      <div class="btn-group btn-group-lg">
        <%= link_to 'Menu', menu_path, class:"btn btn-secondary" %>
        <%= link_to 'Contact', contact_path, class:"btn btn-secondary" %>
      </div>
    </div>
    <div class="col-xs-7">
      <img class="img-responsive img-thumbnail" 
          src="http://loremflickr.com/580/320/restaurents" alt="Restaurent">
    </div>
  </div>
</div>

app/views/wellcome/menu.html.erb
<div class="text-xs-right">
  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort by
    </button>
    <div class="dropdown-menu">
      <%= link_to "Alphabetical", menu_path(sort: "alphabetical", section: params[:section]), class:"dropdown-item" %>
      <%= link_to "View", menu_path(sort: "view", section: params[:section]), class:"dropdown-item" %>
      <%= link_to "Price low to high", menu_path(sort: "price low to high", section: params[:section]), class:"dropdown-item" %>
      <%= link_to "Price high to low", menu_path(sort: "price high to low", section: params[:section]), class:"dropdown-item" %>
    </div>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Filter by cuisine
    </button>
    <div class="dropdown-menu">
      <%= link_to "Pork", menu_path(cuisine: "Pork", section: params[:section]), class:"dropdown-item" %>
      <%= link_to "Chicken", menu_path(cuisine: "Chicken", section: params[:section]), class:"dropdown-item" %>
      <%= link_to "Beef", menu_path(cuisine: "Beef", section: params[:section]), class:"dropdown-item" %>
      <%= link_to "Fish", menu_path(cuisine: "Fish", section: params[:section]), class:"dropdown-item" %>
    </div>
  </div>
</div> <div class="row">
  <div class="col-xl-12">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <%= link_to "All", menu_path, class: 
          "nav-link #{params[:section].blank? ? "active":""}"%>
       </li>
        <% @sections.each do |section| %>
          <li class="nav-item">
            <%= link_to section, menu_path(section: section), class: 
              "nav-link #{section==params[:section] ? "active":""}"%>
          </li>
        <% end %>
    </ul>
  </div>
</div>
<br>
<br>
  <div class=" row card-column">
    <% if @food_items.blank? %>
      <h1 class="text-xs-center">Not Found!</h1>
    <% end %>
    <%= render @food_items %>
  </div>

app/views/wellcome/order.html.erb
<div class="row">
  <h1 class="text-xs-center display-4">Check out</h1>
  <table class="table">
    <thead class="thead-default">
      <tr>
        <th>#</th>
        <th>Dish</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
   <tbody>
     <% @foods.each_with_index do |food, i|  %>
     <tr>
       <th scope="row"><%= i+1 %></th>
        <td><%= food.name %></td>
        <td class="text-xs-right"><%= food.price %> Đ</td>
        <td class="text-xs-right"><%= link_to "Remove",order_path(un_order: food.id) %> </td>
     </tr>
     <% @total_price += food.price %>
     <% end %>
      <tr>
        <td></td>
        <td></td>
        <th class="text-xs-right">Total Price: <%= @total_price + 25000 %> Đ (included delivery cost)</th>
      </tr>
   </tbody>
  </table>
</div>
<h2 class="text-xs-center">Your's Information</h2>
<div class="col-xs-12 col-xl-8 col-xl-offset-2 col-md-6 col-md-offset-3">
  <%= form_for @user, url: user_orders_path(order_list: session[:order_ids].join(" ")), 
    html: {method: :post } do |f| %>
    <div class="form-group">
      <%= f.label :coupon_code,"Coupon code" %>
      <%= f.text_field :coupon_code, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :name,"Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :number,"Phone Number" %>
      <%= f.text_field :number , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_area :address, class: "form-control", size: "60x12" %>
    </div>
    <div class="form_group text-xs-center">
      <%= f.submit "Order", class: "btn btn-secondary btn-lg" %>
      <%= link_to "Back", menu_path, class: "btn btn-secondary btn-lg" %>
    </div>
  <% end %>
</div>
<br>